### ISSUE TITLE
Cannot overwrite existing files when using -Ps

### ISSUE THREAD

**Issue by Onion2222** [EarthScope/dataselect#14]
Hello,

With dataselect3.22 we used to launch the command `dataselect -Ps -rep -nb *` to prune all mseed files in a directory and overwrite them.
However, since dataselect4.0 we are **not able to overwrite existing files when using `-Ps`**

For now we are stuck to using v3.22 because of this behavior.

Thanks for the help,
Arthur

**Comment by chad-earthscope** [comment]
Hi @Onion2222,

> However, since dataselect4.0 we are not able to overwrite existing files when using -Ps

You are not able to use the `-rep` option at all as it was removed in this new major version 4.  Many options were removed. 
 For this one the rationale is that the logic to replace a single (or few) files is easy to orchestrate external to dataselect, and complex scenarios with many input files are pathological and not really useful.

For usage as you illustrate.  A script running dataselect can first rename the input file, have dataselect write the replacement, and then delete the (renamed) input file at the end.  This is exactly what dataselect was doing for this operation.
